displayName: crossover-blacklist
type: middleware
iconPath: .assets/icon.png

import: github.com/kotalco/crossover-blacklist

summary: "crossover blacklist"

testData:
  BlackList:
      - "admin_addPeer"
      - "admin_changeLogLevel"
      - "admin_generateLogBloomCache"
      - "eth_getBlockByNumber"

